# Site settings
title: "Icara 5ish Spellbook"
author: "Typewriter Goblin"
description:
  "A searchable Icara 5ish spell list, sorted by class and level."

baseurl: "/icara-spellbook" # the subpath of your site, e.g. /blog/
url: "https://github.com/Typewritergoblin" # the base hostname & protocol for your site
source-url: "https://github.com/Typewritergoblin/icara-spellbook/"
website: 
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"
